services:
  postgres:
    image: postgres:16
    container_name: payflowmock-postgres
    environment:
      POSTGRES_USER: admin21
      POSTGRES_PASSWORD: admin21
      POSTGRES_DB: PayFlowMock
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin21 -d PayFlowMock"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
